paths:
  js: './src/js/'
  sass: './src/sass/'

outputPaths:
  js: '../../Public/JavaScript/'
  css: '../../Public/Css/'

sass:
  outputStyle: 'expanded'
  indentWidth: 4

cleancss:

autoprefixer:
  browsers: 'last 3 versions, Firefox ESR, not ie < 11, not dead'

uglify:
  output:
    comments: '/^!/'
